### ISSUE TITLE
System.ArgumentException: The path is not of a legal form

### ISSUE THREAD

**Issue by thepwrtank18** [lzinga/MediaSplitter#5]
```
Unhandled Exception: System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.File.GetAttributes(String path)
   at MediaSplitter.Setup.<GetMedia>d__3.MoveNext() in C:\Users\Leo\source\repos\MediaSplitter\MediaSplitter\Setup.cs:line 48
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MediaSplitter.Setup.Execute() in C:\Users\Leo\source\repos\MediaSplitter\MediaSplitter\Setup.cs:line 77
   at MediaSplitter.Program.Main(String[] args) in C:\Users\Leo\source\repos\MediaSplitter\MediaSplitter\Program.cs:line 42
```

This happens regardless of the arguments you put in.

**Comment by Shainure** [comment]
A bit late to the party but for anyone still coming here, the problem is the file name, for the episodes it should be something like `"S01E01-E02"` (split using the - sign), and for the episode names (also necesary) `"First_episode+Second_Episode"`, (split using the +)

**Comment by lzinga** [comment]
> A bit late to the party but for anyone still coming here, the problem is the file name, for the episodes it should be something like `"S01E01-E02"` (split using the - sign), and for the episode names (also necesary) `"First_episode+Second_Episode"`, (split using the +)

Surprised people are still using the program! Glad to see, as mentioned in previous posts, feel free to do a pull request if you have made any significant changes.
